title: Git Hub Practice
author: GitHub User-11
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning how to use Git Hub now. I hope I can make full use of Git Hub.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
